/* Builds ha/honeycomb.html from ha/_template.html plus data/bank.json.

   The bank is embedded rather than fetched so the result stays a single file
   you can drop into /config/www/ — no second asset to keep in sync, and it
   still works opened straight from disk.

     node tools/build-ha.mjs
*/
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');

const bank = JSON.parse(fs.readFileSync(path.join(root, 'data', 'bank.json'), 'utf8'));
const { manifest, puzzles } = bank;

const tplPath = path.join(root, 'ha', '_template.html');
const tpl = fs.readFileSync(tplPath, 'utf8');
if (!tpl.includes('/*__PUZZLES__*/[]')) {
  console.error('template has no /*__PUZZLES__*/[] placeholder');
  process.exit(1);
}

const provenance =
  `/* Puzzle bank: ${manifest.count} puzzles, ${manifest.years_before_repeat} years before repeat.\n` +
  `   Standard: ${manifest.standard.dictionary} (sha256 ${manifest.standard.dictionary_sha256.slice(0, 16)}…),\n` +
  `   ${manifest.standard.frequency_source}, required Zipf >= ${manifest.standard.required_min_zipf},\n` +
  `   accepted Zipf >= ${manifest.standard.bonus_min_zipf}. Built ${manifest.generated_utc}.\n` +
  `   puzzles_sha256 ${manifest.puzzles_sha256}\n` +
  `   Generated by tools/build-ha.mjs — edit _template.html, not this file. */\n`;

const out = tpl.replace('/*__PUZZLES__*/[]', JSON.stringify(puzzles))
                .replace('/* Puzzle data — identical to the full build; see tools/build-ha.mjs. */', provenance.trim());

const dest = path.join(root, 'ha', 'honeycomb.html');
fs.writeFileSync(dest, out);

// prove what landed in the file is exactly what the bank holds
const emitted = out.slice(out.indexOf('const PUZZLES = ') + 'const PUZZLES = '.length);
const parsed = JSON.parse(emitted.slice(0, emitted.indexOf(';\n')));
const canonical = JSON.stringify(parsed.map(p => Object.fromEntries(
  Object.keys(p).sort().map(k => [k, p[k]]))), null, 0);
const sha = crypto.createHash('sha256').update(canonical).digest('hex');
if (sha !== manifest.puzzles_sha256) {
  console.error(`embedded data does not match the bank (${sha.slice(0,16)}… vs ${manifest.puzzles_sha256.slice(0,16)}…)`);
  process.exit(1);
}

console.log(`built ha/honeycomb.html — ${parsed.length} puzzles, ` +
            `${(fs.statSync(dest).size / 1024 / 1024).toFixed(2)} MB, hash verified`);
